### ISSUE TITLE
Setting properties for endpoint dynamically 

### ISSUE THREAD

**Issue by PeterGumball** [AndrejKolar/NetworkStack#2]
Hello Andrej,

find your code very interesting and using it in one of my private project. 

I have one question: What is the best approach to set a property for a endpoint dynamically, for example the host? Right now I have no idea how I can solve it.

Thank you for your help. Greetings from Germany.

Peter

**Comment by AndrejKolar** [comment]
Hey Peter, 

Really glad you like the code. 👍 

That's a great question. 

If you look at the Endpoint code, at the top level you have the `Endpoint` protocol which defines the interface that is used for each concrete endpoint implementation. It defines what each endpoint will have, like a function that returns a request, host, scheme, etc.

Then you have two extensions that set default values for each protocol object. First extension sets the methods for creating requests and mocked requests and the second sets the params that are common for each request, e.g. `"http"` for a scheme.

Third level is the actual implementation, enum which has all the cases for endpoint requests and an extension which implements specific values for that endpoint. In the playground the extension for the `Endpoint` object has the values common for each request and the `UserEndpoint` extension has values for that specific endpoint. 

That's the general idea behind the structure. Now if, for example you wanted to set different hosts for dev, stag & prod, what I would do is create 3 schemes in xCode that have user defined values and then in the Endpoint extension check which scheme I'm using and return a corresponding host string for the host variable.

Another case is If you had two different sets of hosts that multiple endpoints use, what I would do is create two different protocols, both would inherit the Endpoint protocol, they would have two different host values in their extensions and then when you need a specific endpoint you would just implement whichever protocol you need. That would give you a lot of flexibility, but still you get a lot of safety since you are not setting the host each time manually. 

Third option is that you can override all the values at the endpoint implementation level. For example, in the `UserEndpoint`, you can add a host implementation that will override the default value, and that will dynamically set the value just for that specific implementation.

Hope it makes sense, let me know if you have any more questions 👍

**Comment by PeterGumball** [comment]
Thank you for your detailed answer
